import { z } from "zod";
import "zod-openapi/extend";
import { SuccessResponseSchema } from "../../elevenlabs/schemas/elevenlabsSchemas";

// --- Reusable Schemas ---

export const ReplicateAuthSchema = z.object({
  apiKey: z.string().openapi({ description: "Your Replicate API Token." }),
});

// --- Prediction Schemas ---

export const CreatePredictionRequestSchema = ReplicateAuthSchema.extend({
  version: z.string().min(1).openapi({
    description:
      "The ID of the Replicate model version to run (e.g., 'stability-ai/sdxl:c221b2b8...').",
    example:
      "stability-ai/sdxl:c221b2b8ef527988fb59bf24a8b97c4561f1c671f73bd389f866fe846a791195",
  }),
  input: z.record(z.string(), z.any()).openapi({
    description:
      "The model-specific input parameters. Structure depends entirely on the model version.",
    example: { prompt: "An astronaut riding a horse" },
  }),
  webhook: z.string().url().optional().openapi({
    description: "A webhook URL for Replicate to send status updates to.",
  }),
  webhook_events_filter: z
    .array(z.enum(["start", "output", "logs", "completed"]))
    .optional()
    .openapi({
      description: "Events to trigger webhook notifications for.",
    }),
}).openapi({
  description: "Request body for POST /replicate/predictions/create endpoint.",
});

export const GetPredictionStatusRequestSchema = ReplicateAuthSchema.extend({
  taskId: z.string().min(1).openapi({
    description: "The prediction ID obtained from the create endpoint.",
    example: "uf4gsqdjnbuiosm4d5vfzzqvqu", // Example Replicate prediction ID
  }),
}).openapi({
  description: "Request body for POST /replicate/predictions/status endpoint.",
});

// --- Wrapped Response Schemas ---

// Response data schema for task creation
export const CreatePredictionResponseDataSchema = z.object({
  taskId: z.string().openapi({
    description: "The ID of the prediction task started on Replicate.",
  }),
});
export const CreatePredictionResponseSchema = SuccessResponseSchema(
  CreatePredictionResponseDataSchema,
);

// Response data schema for querying task status
export const GetPredictionStatusResponseDataSchema = z
  .object({
    taskId: z.string().openapi({ description: "The Replicate prediction ID." }),
    status: z.enum(["submitted", "processing", "succeed", "failed"]).openapi({
      description:
        "The current status of the task (submitted, processing, succeed, failed).",
    }),
    input: z.record(z.string(), z.any()).optional().openapi({
      description: "The input provided to the model.",
    }),
    output: z.any().optional().openapi({
      description:
        "The output generated by the model. Structure depends on the model.",
    }),
    error: z
      .any()
      .optional()
      .openapi({ description: "Error details, if the task failed." }),
    logs: z
      .string()
      .optional()
      .openapi({ description: "Logs generated by the model." }),
    metrics: z
      .record(z.string(), z.any())
      .optional()
      .openapi({ description: "Performance metrics." }),
    createdAt: z
      .string()
      .optional()
      .openapi({ description: "Timestamp when the task was created." }),
    startedAt: z
      .string()
      .optional()
      .openapi({ description: "Timestamp when the task started processing." }),
    completedAt: z
      .string()
      .optional()
      .openapi({ description: "Timestamp when the task completed." }),
  })
  .passthrough() // Allow any other fields from Replicate
  .openapi({
    description:
      "Standardized response data containing the status and results of a Replicate prediction.",
  });
export const GetPredictionStatusResponseSchema = SuccessResponseSchema(
  GetPredictionStatusResponseDataSchema,
);
