import { z } from "zod";
import "zod-openapi/extend";
import { SuccessResponseSchema } from "../../../../types/api-response";

// Common OpenAPI tags for OpenAI schemas
const OPENAI_TAGS = ["OpenAI"] as const;

// No separate auth schema for this file, included directly

export const AnalyzeImageRequestSchema = z
  .object({
    apiKey: z.string().min(1).openapi({
      description: "Your OpenAI API key.",
      example: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    }),
    imageUrl: z.string().url().openapi({
      description: "The publicly accessible URL of the image to analyze.",
      example:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/1280px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
    }),
    prompt: z.string().optional().openapi({
      description:
        "Optional: Specific question or instruction for the vision model (e.g., `What are the main colors?`). Defaults to generating a description.",
      example: "Describe this image in detail.",
    }),
    model: z.string().optional().default("gpt-4o").openapi({
      description: "Optional: The model to use for analysis.",
      example: "gpt-4o",
    }),
    max_tokens: z.number().int().positive().optional().openapi({
      description:
        "Optional: Maximum number of tokens to generate in the response.",
      example: 300,
    }),
  })
  .openapi({
    description:
      "Request body for analyzing an image using an OpenAI vision model.",
    "x-tags": OPENAI_TAGS,
  });

export const AnalyzeImageResponseDataSchema = z
  .object({
    analysis: z.string().openapi({
      description:
        "The text analysis/description of the image generated by the model.",
      example:
        "The image shows a wooden boardwalk extending through a marshy area...",
    }),
    modelUsed: z.string().openapi({
      description: "The specific OpenAI model that performed the analysis.",
      example: "gpt-4o-2024-05-13",
    }),
    usage: z
      .object({
        prompt_tokens: z.number().int(),
        completion_tokens: z.number().int(),
        total_tokens: z.number().int(),
      })
      .optional()
      .openapi({
        description: "Token usage information for the request.",
      }),
  })
  .passthrough()
  .openapi({
    description:
      "Core response data containing the image analysis and metadata.",
    "x-tags": OPENAI_TAGS,
  });

// Use the standard wrapper
export const AnalyzeImageResponseSchema = SuccessResponseSchema(
  AnalyzeImageResponseDataSchema,
).openapi({
  description: "Standard success response wrapper for image analysis.",
  "x-tags": OPENAI_TAGS,
});

// --- Type Exports ---

export type AnalyzeImageRequest = z.infer<typeof AnalyzeImageRequestSchema>;
export type AnalyzeImageResponse = z.infer<typeof AnalyzeImageResponseSchema>;
